name: Build and Publish Remote-Vector-Index-Builder Faiss Base Snapshot Image to Docker

on:
  push:
    branches:
      - main
    paths:
        - 'base_image/**'
        - '.github/workflows/publish_faiss_base_image.yml'

permissions:
  id-token: write
  contents: read

jobs:
  build-and-publish-faiss-base-image:
    name: Build and Publish Remote-Vector-Index-Builder Faiss Base Snapshot Image
    if: github.repository == 'opensearch-project/remote-vector-index-builder'
    runs-on:
      group: selfhosted-gpu-runners
      labels: g62xlarge

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            submodules: 'recursive'
            path: 'rvib'

      - name: Build Docker Image
        run : |
            cd rvib
            docker build  -f ./base_image/build_scripts/Dockerfile . -t opensearchstaging/remote-vector-index-builder:faiss-base-snapshot
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: ${{ secrets.REMOTE_VECTOR_DOCKER_ROLE }}
            aws-region: us-east-1

      - name: Retrieve Values
        id: retrieve-values
        run: |
            DOCKERHUB_PASSWORD=`aws secretsmanager get-secret-value --secret-id jenkins-staging-dockerhub-credential --query SecretString --output text`
            echo "::add-mask::$DOCKERHUB_PASSWORD"
            echo "dockerhub-password=$DOCKERHUB_PASSWORD" >> $GITHUB_OUTPUT
          
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.REMOTE_VECTOR_DOCKER_USERNAME }}
            password: ${{ steps.retrieve-values.outputs.dockerhub-password }}

      - name: Push Docker Image
        run : |
          docker push opensearchstaging/remote-vector-index-builder:faiss-base-snapshot

      - name: Runner Cleanups
        if: always()
        run: |
          # Docker cleanup
          docker logout
          docker system prune -a -f
          
          # Workspace cleanup
          rm -rf ${{ github.workspace }}/*
  
  # Trigger build of core image since base image is changed
  build-and-publish-core-image:
    needs: build-and-publish-faiss-base-image
    uses: ./.github/workflows/publish_remote_core_image.yml
    secrets:
      REMOTE_VECTOR_DOCKER_ROLE: ${{ secrets.REMOTE_VECTOR_DOCKER_ROLE }}
      REMOTE_VECTOR_DOCKER_USERNAME: ${{ secrets.REMOTE_VECTOR_DOCKER_USERNAME }}
